# ref: https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#appspec-hooks-server
version: 0.0
os: linux
#files:
#  - source: /
#    destination: /tmp/yelb
hooks:
  BeforeInstall:
    - location: deployments/platformdeployment/Linux/cleanup.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: deployments/platformdeployment/Linux/single-instance-deployment.sh
      timeout: 3600
      runas: root
